name: sight_calibrator
description: Application for calibration of your Red Dot Sight, Holographic Sight, Scope and other.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  path: ^1.8.2
  cupertino_icons: ^1.0.2
  floor: ^1.4.1
  sqflite: ^2.2.6
  shared_preferences: ^2.1.0
  intl: ^0.17.0
  package_info_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  floor_generator: ^1.4.1
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false